
import React, { useState, useCallback } from 'react';
import { TextIcon } from './icons/TextIcon';
import { FileIcon } from './icons/FileIcon';

interface InputAreaProps {
  onAnalyze: (texts: string[]) => void;
  isLoading: boolean;
}

const InputArea: React.FC<InputAreaProps> = ({ onAnalyze, isLoading }) => {
  const [activeTab, setActiveTab] = useState<'text' | 'file'>('text');
  const [textInput, setTextInput] = useState('');
  const [fileName, setFileName] = useState('');

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      setFileName(file.name);
      const reader = new FileReader();
      reader.onload = (e) => {
        const content = e.target?.result as string;
        setTextInput(content);
      };
      reader.readAsText(file);
    }
  };

  const handleSubmit = () => {
    const texts = textInput.split('\n').map(line => line.trim()).filter(line => line.length > 0);
    onAnalyze(texts);
  };

  // Fix: Use React.ReactElement to solve "Cannot find namespace 'JSX'".
  const TabButton = useCallback(({ id, label, icon }: { id: 'text' | 'file', label: string, icon: React.ReactElement }) => (
    <button
      onClick={() => setActiveTab(id)}
      className={`flex items-center space-x-2 px-4 py-2 text-sm font-medium rounded-t-lg border-b-2 transition-colors duration-200 ${
        activeTab === id
          ? 'border-blue-500 text-blue-600 dark:text-blue-400'
          : 'border-transparent text-gray-500 hover:text-gray-700 dark:hover:text-gray-300'
      }`}
    >
      {icon}
      <span>{label}</span>
    </button>
  ), [activeTab]);


  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
      <div className="border-b border-gray-200 dark:border-gray-700">
        <nav className="-mb-px flex space-x-4">
          <TabButton id="text" label="Direct Input" icon={<TextIcon />} />
          <TabButton id="file" label="Upload File" icon={<FileIcon />} />
        </nav>
      </div>

      <div className="mt-6">
        {activeTab === 'text' && (
          <textarea
            value={textInput}
            onChange={(e) => setTextInput(e.target.value)}
            placeholder="Enter text here, one entry per line...
For example:
The service was excellent, I am very happy!
The product broke after just one week.
This is a standard product, nothing special."
            className="w-full h-48 p-3 border border-gray-300 dark:border-gray-600 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition bg-gray-50 dark:bg-gray-700"
            disabled={isLoading}
          />
        )}
        {activeTab === 'file' && (
          <div className="flex items-center justify-center w-full">
            <label htmlFor="dropzone-file" className="flex flex-col items-center justify-center w-full h-48 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:hover:bg-bray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600 transition">
              <div className="flex flex-col items-center justify-center pt-5 pb-6">
                <FileIcon />
                <p className="mb-2 text-sm text-gray-500 dark:text-gray-400">
                  <span className="font-semibold">Click to upload</span> or drag and drop
                </p>
                <p className="text-xs text-gray-500 dark:text-gray-400">.txt file (one entry per line)</p>
              </div>
              <input id="dropzone-file" type="file" accept=".txt" className="hidden" onChange={handleFileChange} disabled={isLoading} />
              {fileName && <p className="text-sm text-gray-600 dark:text-gray-300 mt-2">{fileName}</p>}
            </label>
          </div>
        )}
      </div>

      <div className="mt-6 flex justify-end">
        <button
          onClick={handleSubmit}
          disabled={isLoading || textInput.trim().length === 0}
          className="px-6 py-2.5 bg-blue-600 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-75 disabled:bg-gray-400 disabled:cursor-not-allowed transition-all duration-300"
        >
          {isLoading ? 'Analyzing...' : 'Analyze Text'}
        </button>
      </div>
       <div className="mt-4 text-xs text-gray-500 dark:text-gray-400">
          <p><span className="font-semibold">Note:</span> Confidence scores and explanations are generated by an AI model and should be considered as estimations. Always review critical results.</p>
        </div>
    </div>
  );
};

export default InputArea;
